version: '3.9'
services:
  diabetes-prediction:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - VIRTUAL_ENV=/opt/venv
      - PATH=/opt/venv/bin:$PATH
      - PORT=8000
    volumes:
      - .:/app
    command: ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "main:app"]
